# Generated by Django 2.2.6 on 2020-05-15 14:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facebook', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pub',
            new_name='pub_model',
        ),
    ]
